T-2: documentation update
Kiszkacy/AI-controlled-models-analysis pull request #3
Opened 2024-05-18 16:19 UTC by Kiszkacy

This pull request entails updating all README files to align with the creation of GitHub Wiki pages. The changes aim to ensure consistency and clarity between the project's documentation and its GitHub Pages.

2024-05-19 21:16 UTC, MasterHamster42 approved these changes, later dismissed
LGTM

2024-06-05 17:33 UTC, MartynaSokolowska requested changes

2024-06-05 17:33 UTC, MartynaSokolowska commented on README.md
> +The main goal of this project is to create an application capable of simulating a dynamic environment, allowing observation and analysis of behaviors and interactions among virtual creatures (agents)
each type of agent

2024-06-05 17:40 UTC, MartynaSokolowska approved these changes

2024-06-05 17:40 UTC, Kiszkacy commented on README.md
> +The main goal of this project is to create an application capable of simulating a dynamic environment, allowing observation and analysis of behaviors and interactions among virtual creatures (agents)
fixed

2024-06-12 14:41 UTC, anian3 approved these changes

2024-06-12 19:19 UTC, merged